# Generated by Django 5.2.16 on 2026-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('apartment', 'Apartment')], max_length=20),
        ),
    ]
