# Generated by Django 5.1.15 on 2026-09-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='property_type',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('apartment', 'Apartment'), ('hostel', 'Hostel')], max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
