# Generated by Django 5.2.16 on 2026-09-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0003_servicerequest_rename_message_to_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
