# Generated by Django 5.1.15 on 2026-09-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('service_requests', '0004_servicerequest_guest_email_servicerequest_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='service_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='review',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='service_requests.servicerequest'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('visible', 'Published (Legacy)'), ('hidden', 'Hidden (Legacy)'), ('removed', 'Removed (Legacy)')], default='pending', max_length=20),
        ),
    ]
