# Generated by Django 5.1.15 on 2026-09-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_email_company_phone_company_specialties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('decoration', 'Decoration')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'ordering', 'name'),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_covers/'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_gallery/')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='companies.company')),
            ],
            options={
                'ordering': ('ordering', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_memberships', to='companies.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to='companies.service')),
            ],
            options={
                'ordering': ('ordering', 'service__name'),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='service_items',
            field=models.ManyToManyField(blank=True, related_name='companies', through='companies.CompanyService', to='companies.service'),
        ),
        migrations.AddConstraint(
            model_name='companyservice',
            constraint=models.UniqueConstraint(fields=('company', 'service'), name='unique_company_service'),
        ),
    ]
