# Generated by Django 5.2.16 on 2026-09-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_service_company_cover_image_company_service_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
