# Generated by Django 5.2.16 on 2026-09-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='companies.service'),
        ),
    ]
